### ISSUE TITLE
Discart invalid request in document macro

### ISSUE THREAD

**Issue by Danielwsx64** [brainn-co/xcribe#19]
When a conn is given to `ConnParser` the function `execute` just extract the needed information about connection. It doesnt validate if resulted information fulfill all requirements to be converted in an specific format (OpenAPI or Blueprint). We must create a specify module for each format and validate the result information to certify that is all right.

eg

```elixir
defmodule Xcribe.ConnParser do
  def execute(conn, description \\ "") do
     result = ... all current stuff
      
     Xcribe.config.doc_format()
     |> result_validator_for()
     |> apply(:validate_request,[result])  # return {:ok, %Request{}} or {:error, [error list]}
  end

  defp result_validator_for(:api_blueprint), do: Xcribe.ApiBlueprint.Validator
  defp result_validator_for(:swagger), do: Xcribe.Swagger.Validator
end
```

With this validator we can discard invalid requests at `document` macro call:

```elixir
defmodule Xcribe.Helpers.Document do
    ...
        case ConnParser.execute(conn, request_description(options)) do
           {:ok, request} -> Recorder.save()
           {:error, errors} -> log_error(errors)
        end
end
```

Actually the know invalid information is:
- Any content format except json and raw text (request and response)
- Route not found

We need think about other invalid information we can face.

**Comment by adrianolisboa** [comment]
When `resp_body` has a invalid content and `Jason` library raises an exception the documentation isn't generated and sometimes we just miss those messages in pipelines.

Whould be good to have an opcional option with XCribe to force tests to be broken when this occurs.

This way we can track documentation errors in pipelines.

**Comment by Danielwsx64** [comment]
@adrianolisboa I create a new issue to meet your request #56

**Comment by Danielwsx64** [comment]
#28
