### ISSUE TITLE
Order possible route responses

### ISSUE THREAD

**Issue by brosquinha** [brainn-co/xcribe#2]
Currently, Xcribe does not enforce a specific order of possible route responses. Consequently, git diffs of Blueprint file can be quite difficult to read.

A suggestion would be to enforce a response order in order to avoid this confusion.

**Comment by Danielwsx64** [comment]
Maybe we can order the requests by  the name?

**Comment by Danielwsx64** [comment]
https://github.com/brainn-co/xcribe/pull/37
