### ISSUE TITLE
Problem in the versions before 1.4 of phoenix

### ISSUE THREAD

**Issue by iagoEffting** [brainn-co/xcribe#23]
When I try to configure in the version before 1.4 I have take an error :

![image](https://user-images.githubusercontent.com/2313911/78901273-765c0000-7a4e-11ea-8109-11271ddb7889.png)

The problem is in the `__match_route__`. My shot is: the phoenix 1.4 has another away to do that.

Want more investigation

**Comment by Danielwsx64** [comment]
@iagoEffting as Phoenix 1.5 was released I think would be better focus on other bug issues. Nowadays no one is using Xcribe with Phoenix <1.4.

So I'll label this issue as `wontfix` and we can discuss this again in the future.
