### ISSUE TITLE
Blueprint file has unicode issues

### ISSUE THREAD

**Issue by brosquinha** [brainn-co/xcribe#3]
If any unicode character is given to `document` function on tests, the Blueprint file gets an encoding error character. For instance:

```elixir
response =
        conn
        |> get(cookies_path(conn, :index, %{id: UUID.generate()}))
        |> document(as: "atributos inválidos")
        |> json_response(422)
```

Results:

```markdown
+ Request atributos inv� lidos (text/plain)
+ Response 422 (application/json; charset=utf-8)
    + Headers

            cache-control: max-age=0, private, must-revalidate

    + Body
```

The expected behaviour is to replicate the string given to `document` in generated document.

**Comment by Danielwsx64** [comment]
How can I reproduce this issue?

**Comment by Danielwsx64** [comment]
I tried to reproduce the issue but `Xcribe` is replicating the string correctly.
