### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by thiamsantos** [brainn-co/xcribe#31]
## Motivation

![image](https://user-images.githubusercontent.com/13632762/81962101-a36d7680-95e9-11ea-9e21-34c4c95f0fd2.png)

Today all the modules and functions of xcribe are part of the documentation. However we should only document and expose the functions that we really want to user to be interacting. So we are free to change the private interface without having to do major releases, also we don't confuse the users with a lot of unnecessary information.

## Proposed solution

Mark all modules with `@moduledoc false` except the ones that the user interacts:

- `Xcribe.Formatter`
- `Xcribe.Information`
- `Xcribe.Helpers.Document`

Also another suggestion, would move the helpers from `Xcribe.Helpers.Document` to `Xcribe` exposing the main interface in the main module.

WDYT? cc: @Danielwsx64 @brosquinha

**Comment by Danielwsx64** [comment]
https://github.com/brainn-co/xcribe/pull/37
