### ISSUE TITLE
Use Schema and Body on payload section

### ISSUE THREAD

**Issue by Danielwsx64** [brainn-co/xcribe#4]
Actually [Payload Section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-payload-section)  just define [Headers section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-headers-section) and [Attributes section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-attributes-section)

To handle full information [Body section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-body-section) and [Schema section](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-schema-section) should be implemented.

**Comment by brosquinha** [comment]
Swagger also works with schemas, so a generic implementation of schemas would be the best approach.
